import type { ThemeDefinition } from "../types.ts";

/**
 * Clean DeepSeek-inspired blue light theme: the product's brand palette on a
 * neutral-bluish light base.
 */
export const deepseek: ThemeDefinition = Object.freeze({
  id: "deepseek",
  colorScheme: "light",
  tokens: Object.freeze({
    "--dsw-alias-bg-base": "#ffffff",
    "--dsw-alias-bg-layer-1": "#ffffff",
    "--dsw-alias-bg-layer-2": "#f5f6f7",
    "--dsw-alias-bg-layer-3": "#ededf0",
    "--dsw-alias-bg-overlay": "#ededed",
    "--dsw-alias-label-primary": "#1f1f1f",
    "--dsw-alias-label-secondary": "#616367",
    "--dsw-alias-label-tertiary": "#6b6d72",
    "--dsw-alias-brand-primary": "#4176e6",
    "--dsw-alias-state-business-primary": "#4176e6",
    "--dsw-alias-state-success-primary": "#1dab52",
    "--dsw-alias-state-warn-primary": "#ca8208",
    "--dsw-alias-state-error-primary": "#ec1313",
    "--dsw-alias-border-l1": "rgba(0, 0, 0, 0.04)",
    "--dsw-alias-border-l2": "rgba(0, 0, 0, 0.1)",
    "--dsw-alias-interactive-bg-hover": "rgba(38, 49, 72, 0.06)",
    "--dsw-alias-interactive-bg-active": "rgba(38, 49, 72, 0.1)",
    "--dsw-alias-button-primary-fill": "#1f1f1f",
    "--dsw-alias-button-primary-hover": "#3d3d40",
    "--dsw-alias-markdown-code-block": "#fafafa",
    "--dsw-alias-markdown-code-block-banner": "#fafafa",
    "--dsw-alias-markdown-inline-code": "#f5f5f5",
    "--dsw-alias-markdown-tag": "#ededed",
    "--dsw-alias-scrollbar-bg-l1": "#e5e5e5",
    "--dsw-alias-scrollbar-hover-l1": "#d4d4d4",
    "--dsw-alias-tooltip-bg": "#212121",
    "--dsw-specific-bubble": "#edf3fe",
    "--dsw-specific-bubble-highlight": "#d3e2ff",
    "--dsw-specific-sidebar-fill": "#fafafa",
    "--dsw-specific-sidebar-nav-item-active": "#f5f5f5",
    "--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
    "--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
    "--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
    "--dsw-alias-bg-module-platform": "#f9fafb",
    "--dsw-alias-bg-multi-select": "#f9fafb",
    "--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
    "--dsw-alias-border-l3": "rgba(0, 0, 0, 0.12)",
    "--dsw-alias-border-l4": "rgba(0, 0, 0, 0.16)",
    "--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
    "--dsw-alias-button-info-fill": "#4176e6",
    "--dsw-alias-button-info-hover": "#2f63d4",
    "--dsw-alias-button-elevated-fill": "#ffffff",
    "--dsw-alias-button-floating-fill": "#ffffff",
    "--dsw-alias-button-floating-hover": "#f1f3f5",
    "--dsw-alias-interactive-bg-hover-solid": "#f1f3f5",
    "--dsw-alias-interactive-bg-hover-danger": "rgba(236, 19, 19, 0.05)",
    "--dsw-alias-interactive-bg-hover-accent": "rgba(38, 49, 72, 0.14)",
    "--dsw-alias-label-caption": "#6b6d72",
    "--dsw-alias-label-primary-inverted": "#ffffff",
    "--dsw-alias-label-primary-dimmed": "#15171a",
    "--dsw-alias-label-dimmed": "#e5e5e5",
    "--dsw-alias-markdown-citation": "#f5f5f5",
    "--dsw-alias-markdown-code-segment-selected": "#ffffff",
    "--dsw-alias-markdown-code-segment-unselected": "#f1f3f5",
    "--dsw-alias-markdown-placeholder": "#f9fafb",
    "--dsw-alias-scrollbar-bg-l2": "#e5e5e5",
    "--dsw-alias-scrollbar-hover-l2": "#d4d4d4",
    "--dsw-alias-state-success-secondary": "#4ade80",
    "--dsw-alias-state-warn-secondary": "#fbbf24",
    "--dsw-alias-state-error-secondary": "#f87171",
    "--dsw-alias-state-success-tertiary": "#e6fbee",
    "--dsw-alias-state-warn-tertiary": "#fef3e2",
    "--dsw-alias-state-business-tertiary": "#e7effd",
    "--dsw-alias-toast-bg": "#333333",
    "--dsw-specific-input-major": "#ffffff",
    "--dsw-specific-login-input": "#fafafa",
    "--dsw-specific-menu": "#ededf0",
    "--dsw-specific-selector": "#f9fafb",
    "--dsw-specific-sidebar-nav-item-hover": "#f1f3f5",
    "--dsw-specific-tip": "#f9fafb",
  }),
});
