import type { ThemeDefinition } from "../types.ts";

/**
 * Low-color, distraction-free light theme: monochrome surfaces with muted
 * state colors, tuned for focus.
 */
export const minimal: ThemeDefinition = Object.freeze({
  id: "minimal",
  colorScheme: "light",
  tokens: Object.freeze({
    "--dsw-alias-bg-base": "#fafafa",
    "--dsw-alias-bg-layer-1": "#fafafa",
    "--dsw-alias-bg-layer-2": "#f4f4f4",
    "--dsw-alias-bg-layer-3": "#ededed",
    "--dsw-alias-bg-overlay": "#e8e8e8",
    "--dsw-alias-label-primary": "#171717",
    "--dsw-alias-label-secondary": "#5c5c5c",
    "--dsw-alias-label-tertiary": "#8a8a8a",
    "--dsw-alias-brand-primary": "#171717",
    "--dsw-alias-state-business-primary": "#4a4a4a",
    "--dsw-alias-state-success-primary": "#3d7a4d",
    "--dsw-alias-state-warn-primary": "#8a6d3b",
    "--dsw-alias-state-error-primary": "#a04a4a",
    "--dsw-alias-border-l1": "rgba(0, 0, 0, 0.05)",
    "--dsw-alias-border-l2": "rgba(0, 0, 0, 0.1)",
    "--dsw-alias-interactive-bg-hover": "rgba(0, 0, 0, 0.04)",
    "--dsw-alias-interactive-bg-active": "rgba(0, 0, 0, 0.08)",
    "--dsw-alias-button-primary-fill": "#171717",
    "--dsw-alias-button-primary-hover": "#333333",
    "--dsw-alias-markdown-code-block": "#f4f4f4",
    "--dsw-alias-markdown-code-block-banner": "#f4f4f4",
    "--dsw-alias-markdown-inline-code": "#ededed",
    "--dsw-alias-markdown-tag": "#ededed",
    "--dsw-alias-scrollbar-bg-l1": "#d9d9d9",
    "--dsw-alias-scrollbar-hover-l1": "#c8c8c8",
    "--dsw-alias-tooltip-bg": "#262626",
    "--dsw-specific-bubble": "#f4f4f4",
    "--dsw-specific-bubble-highlight": "#ededed",
    "--dsw-specific-sidebar-fill": "#f4f4f4",
    "--dsw-specific-sidebar-nav-item-active": "#e8e8e8",
    "--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.24)",
    "--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.12)",
    "--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
    "--dsw-alias-bg-module-platform": "#f4f4f4",
    "--dsw-alias-bg-multi-select": "#f4f4f4",
    "--dsw-alias-bg-skeleton": "rgba(0, 0, 0, 0.04)",
    "--dsw-alias-border-l3": "rgba(0, 0, 0, 0.12)",
    "--dsw-alias-border-l4": "rgba(0, 0, 0, 0.16)",
    "--dsw-alias-border-inverted": "rgba(0, 0, 0, 0)",
    "--dsw-alias-button-info-fill": "#4a4a4a",
    "--dsw-alias-button-info-hover": "#5c5c5c",
    "--dsw-alias-button-elevated-fill": "#fafafa",
    "--dsw-alias-button-floating-fill": "#fafafa",
    "--dsw-alias-button-floating-hover": "#f4f4f4",
    "--dsw-alias-interactive-bg-hover-solid": "#f4f4f4",
    "--dsw-alias-interactive-bg-hover-danger": "rgba(160, 74, 74, 0.08)",
    "--dsw-alias-interactive-bg-hover-accent": "rgba(0, 0, 0, 0.12)",
    "--dsw-alias-label-caption": "#8a8a8a",
    "--dsw-alias-label-primary-inverted": "#ffffff",
    "--dsw-alias-label-primary-dimmed": "#333333",
    "--dsw-alias-label-dimmed": "#ededed",
    "--dsw-alias-markdown-citation": "#f4f4f4",
    "--dsw-alias-markdown-code-segment-selected": "#ffffff",
    "--dsw-alias-markdown-code-segment-unselected": "#f4f4f4",
    "--dsw-alias-markdown-placeholder": "#f4f4f4",
    "--dsw-alias-scrollbar-bg-l2": "#d9d9d9",
    "--dsw-alias-scrollbar-hover-l2": "#c8c8c8",
    "--dsw-alias-state-success-secondary": "#5c9a6d",
    "--dsw-alias-state-warn-secondary": "#a68a4f",
    "--dsw-alias-state-error-secondary": "#b46a6a",
    "--dsw-alias-state-success-tertiary": "#e8f0ea",
    "--dsw-alias-state-warn-tertiary": "#f2ece2",
    "--dsw-alias-state-business-tertiary": "#eaeaea",
    "--dsw-alias-toast-bg": "#262626",
    "--dsw-specific-input-major": "#ffffff",
    "--dsw-specific-login-input": "#fafafa",
    "--dsw-specific-menu": "#ededed",
    "--dsw-specific-selector": "#f4f4f4",
    "--dsw-specific-sidebar-nav-item-hover": "#e8e8e8",
    "--dsw-specific-tip": "#f4f4f4",
  }),
});
