import type { ThemeDefinition } from "../types.ts";

/**
 * Nord: arctic north-blues — nord0 surfaces, frost nord8 accent, aurora
 * state colors.
 *
 * Tertiary/caption take frost nord9 `#81a1c1`: nord3 `#4c566a` reaches only
 * ~1.7:1 on the nord0–nord2 ladder, so nord3 is confined to layer-3/overlay/
 * scrollbar tracks and never sits under text. Borders and interactions use
 * translucent nord6 overlays. Upstream paints code blocks and the sidebar
 * the same nord0 as the base; depth comes from nord1/nord2 raised surfaces.
 * Scrollbar hover `#5e6b82` is nord3 lightened.
 */
export const nord: ThemeDefinition = Object.freeze({
  id: "nord",
  colorScheme: "dark",
  tokens: Object.freeze({
    "--dsw-alias-bg-base": "#2e3440",
    "--dsw-alias-bg-layer-1": "#3b4252",
    "--dsw-alias-bg-layer-2": "#434c5e",
    "--dsw-alias-bg-layer-3": "#4c566a",
    "--dsw-alias-bg-overlay": "#566073",
    "--dsw-alias-label-primary": "#eceff4",
    "--dsw-alias-label-secondary": "#d8dee9",
    "--dsw-alias-label-tertiary": "#81a1c1",
    "--dsw-alias-brand-primary": "#88c0d0",
    "--dsw-alias-state-business-primary": "#5e81ac",
    "--dsw-alias-state-success-primary": "#a3be8c",
    "--dsw-alias-state-warn-primary": "#ebcb8b",
    "--dsw-alias-state-error-primary": "#bf616a",
    "--dsw-alias-border-l1": "rgba(236, 239, 244, 0.08)",
    "--dsw-alias-border-l2": "rgba(236, 239, 244, 0.15)",
    "--dsw-alias-interactive-bg-hover": "rgba(236, 239, 244, 0.06)",
    "--dsw-alias-interactive-bg-active": "rgba(236, 239, 244, 0.12)",
    "--dsw-alias-button-primary-fill": "#88c0d0",
    "--dsw-alias-button-primary-hover": "#9ccdda",
    "--dsw-alias-markdown-code-block": "#272e38",
    "--dsw-alias-markdown-code-block-banner": "#3b4252",
    "--dsw-alias-markdown-inline-code": "#3b4252",
    "--dsw-alias-markdown-tag": "#3b4252",
    "--dsw-alias-scrollbar-bg-l1": "#4c566a",
    "--dsw-alias-scrollbar-hover-l1": "#5e6b82",
    "--dsw-alias-tooltip-bg": "#434c5e",
    "--dsw-specific-bubble": "#3b4252",
    "--dsw-specific-bubble-highlight": "#434c5e",
    "--dsw-specific-sidebar-fill": "#2e3440",
    "--dsw-specific-sidebar-nav-item-active": "#3b4252",
    "--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
    "--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
    "--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
    "--dsw-alias-bg-module-platform": "#3b4252",
    "--dsw-alias-bg-multi-select": "#3b4252",
    "--dsw-alias-bg-skeleton": "rgba(236, 239, 244, 0.08)",
    "--dsw-alias-border-l3": "rgba(236, 239, 244, 0.22)",
    "--dsw-alias-border-l4": "rgba(236, 239, 244, 0.28)",
    "--dsw-alias-border-inverted": "rgba(236, 239, 244, 0.1)",
    "--dsw-alias-button-info-fill": "#5e81ac",
    "--dsw-alias-button-info-hover": "#7391b9",
    "--dsw-alias-button-elevated-fill": "#3b4252",
    "--dsw-alias-button-floating-fill": "#3b4252",
    "--dsw-alias-button-floating-hover": "#434c5e",
    "--dsw-alias-interactive-bg-hover-solid": "#434c5e",
    "--dsw-alias-interactive-bg-hover-danger": "rgba(191, 97, 106, 0.18)",
    "--dsw-alias-interactive-bg-hover-accent": "rgba(136, 192, 208, 0.24)",
    "--dsw-alias-label-caption": "#81a1c1",
    "--dsw-alias-label-primary-inverted": "#2e3440",
    "--dsw-alias-label-primary-dimmed": "#d8dee9",
    "--dsw-alias-label-dimmed": "#434c5e",
    "--dsw-alias-markdown-citation": "#3b4252",
    "--dsw-alias-markdown-code-segment-selected": "#434c5e",
    "--dsw-alias-markdown-code-segment-unselected": "#2e3440",
    "--dsw-alias-markdown-placeholder": "#3b4252",
    "--dsw-alias-scrollbar-bg-l2": "#4c566a",
    "--dsw-alias-scrollbar-hover-l2": "#5e6b82",
    "--dsw-alias-state-success-secondary": "#b7d0a5",
    "--dsw-alias-state-warn-secondary": "#f2dcae",
    "--dsw-alias-state-error-secondary": "#d47f87",
    "--dsw-alias-state-success-tertiary": "#2f3b33",
    "--dsw-alias-state-warn-tertiary": "#3f3a2e",
    "--dsw-alias-state-business-tertiary": "#2c3a4a",
    "--dsw-alias-toast-bg": "#434c5e",
    "--dsw-specific-input-major": "#434c5e",
    "--dsw-specific-login-input": "#2e3440",
    "--dsw-specific-menu": "#434c5e",
    "--dsw-specific-selector": "#3b4252",
    "--dsw-specific-sidebar-nav-item-hover": "#3b4252",
    "--dsw-specific-tip": "#3b4252",
  }),
});
