import type { ThemeDefinition } from "../types.ts";

/**
 * Cool, restrained Nordic palette: the Nord scheme's polar-night surfaces,
 * snow-storm text, and frost accents.
 */
export const nord: ThemeDefinition = Object.freeze({
  id: "nord",
  colorScheme: "dark",
  tokens: Object.freeze({
    "--dsw-alias-bg-base": "#2e3440",
    "--dsw-alias-bg-layer-1": "#353c4a",
    "--dsw-alias-bg-layer-2": "#3b4252",
    "--dsw-alias-bg-layer-3": "#434c5e",
    "--dsw-alias-bg-overlay": "#4c566a",
    "--dsw-alias-label-primary": "#d8dee9",
    "--dsw-alias-label-secondary": "#aebbcb",
    "--dsw-alias-label-tertiary": "#616e88",
    "--dsw-alias-brand-primary": "#88c0d0",
    "--dsw-alias-state-business-primary": "#81a1c1",
    "--dsw-alias-state-success-primary": "#a3be8c",
    "--dsw-alias-state-warn-primary": "#ebcb8b",
    "--dsw-alias-state-error-primary": "#bf616a",
    "--dsw-alias-border-l1": "rgba(216, 222, 233, 0.08)",
    "--dsw-alias-border-l2": "rgba(216, 222, 233, 0.15)",
    "--dsw-alias-interactive-bg-hover": "rgba(216, 222, 233, 0.06)",
    "--dsw-alias-interactive-bg-active": "rgba(216, 222, 233, 0.12)",
    "--dsw-alias-button-primary-fill": "#88c0d0",
    "--dsw-alias-button-primary-hover": "#97ccda",
    "--dsw-alias-markdown-code-block": "#292e39",
    "--dsw-alias-markdown-code-block-banner": "#292e39",
    "--dsw-alias-markdown-inline-code": "#3b4252",
    "--dsw-alias-markdown-tag": "#3b4252",
    "--dsw-alias-scrollbar-bg-l1": "#4c566a",
    "--dsw-alias-scrollbar-hover-l1": "#616e88",
    "--dsw-alias-tooltip-bg": "#3b4252",
    "--dsw-specific-bubble": "#3b4252",
    "--dsw-specific-bubble-highlight": "#434c5e",
    "--dsw-specific-sidebar-fill": "#292e39",
    "--dsw-specific-sidebar-nav-item-active": "#3b4252",
    "--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
    "--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
    "--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
    "--dsw-alias-bg-module-platform": "#3b4252",
    "--dsw-alias-bg-multi-select": "#353c4a",
    "--dsw-alias-bg-skeleton": "rgba(216, 222, 233, 0.08)",
    "--dsw-alias-border-l3": "rgba(216, 222, 233, 0.22)",
    "--dsw-alias-border-l4": "rgba(216, 222, 233, 0.28)",
    "--dsw-alias-border-inverted": "rgba(216, 222, 233, 0.1)",
    "--dsw-alias-button-info-fill": "#81a1c1",
    "--dsw-alias-button-info-hover": "#93b0cd",
    "--dsw-alias-button-elevated-fill": "#353c4a",
    "--dsw-alias-button-floating-fill": "#3b4252",
    "--dsw-alias-button-floating-hover": "#434c5e",
    "--dsw-alias-interactive-bg-hover-solid": "#434c5e",
    "--dsw-alias-interactive-bg-hover-danger": "rgba(191, 97, 106, 0.18)",
    "--dsw-alias-interactive-bg-hover-accent": "rgba(136, 192, 208, 0.18)",
    "--dsw-alias-label-caption": "#616e88",
    "--dsw-alias-label-primary-inverted": "#2e3440",
    "--dsw-alias-label-primary-dimmed": "#aebbcb",
    "--dsw-alias-label-dimmed": "#434c5e",
    "--dsw-alias-markdown-citation": "#3b4252",
    "--dsw-alias-markdown-code-segment-selected": "#434c5e",
    "--dsw-alias-markdown-code-segment-unselected": "#292e39",
    "--dsw-alias-markdown-placeholder": "#3b4252",
    "--dsw-alias-scrollbar-bg-l2": "#4c566a",
    "--dsw-alias-scrollbar-hover-l2": "#616e88",
    "--dsw-alias-state-success-secondary": "#b1d19b",
    "--dsw-alias-state-warn-secondary": "#ecd3a0",
    "--dsw-alias-state-error-secondary": "#cf8a94",
    "--dsw-alias-state-success-tertiary": "#2f3e2f",
    "--dsw-alias-state-warn-tertiary": "#3e382a",
    "--dsw-alias-state-business-tertiary": "#2e3b47",
    "--dsw-alias-toast-bg": "#3b4252",
    "--dsw-specific-input-major": "#434c5e",
    "--dsw-specific-login-input": "#292e39",
    "--dsw-specific-menu": "#434c5e",
    "--dsw-specific-selector": "#3b4252",
    "--dsw-specific-sidebar-nav-item-hover": "#3b4252",
    "--dsw-specific-tip": "#3b4252",
  }),
});
