import type { ThemeDefinition } from "../types.ts";

/**
 * True-black theme for OLED displays: pure #000 backgrounds with maximum
 * contrast foregrounds, saving power on emissive panels.
 */
export const oled: ThemeDefinition = Object.freeze({
  id: "oled",
  colorScheme: "dark",
  tokens: Object.freeze({
    "--dsw-alias-bg-base": "#000000",
    "--dsw-alias-bg-layer-1": "#050505",
    "--dsw-alias-bg-layer-2": "#0a0a0a",
    "--dsw-alias-bg-layer-3": "#0f0f0f",
    "--dsw-alias-bg-overlay": "#171717",
    "--dsw-alias-label-primary": "#f0f0f0",
    "--dsw-alias-label-secondary": "#a0a0a0",
    "--dsw-alias-label-tertiary": "#7b7b7b",
    "--dsw-alias-brand-primary": "#ffffff",
    "--dsw-alias-state-business-primary": "#e0e0e0",
    "--dsw-alias-state-success-primary": "#34d399",
    "--dsw-alias-state-warn-primary": "#fbbf24",
    "--dsw-alias-state-error-primary": "#f87171",
    "--dsw-alias-border-l1": "rgba(255, 255, 255, 0.1)",
    "--dsw-alias-border-l2": "rgba(255, 255, 255, 0.18)",
    "--dsw-alias-interactive-bg-hover": "rgba(255, 255, 255, 0.08)",
    "--dsw-alias-interactive-bg-active": "rgba(255, 255, 255, 0.16)",
    "--dsw-alias-button-primary-fill": "#ffffff",
    "--dsw-alias-button-primary-hover": "#d4d4d4",
    "--dsw-alias-markdown-code-block": "#0a0a0a",
    "--dsw-alias-markdown-code-block-banner": "#0a0a0a",
    "--dsw-alias-markdown-inline-code": "#141414",
    "--dsw-alias-markdown-tag": "#141414",
    "--dsw-alias-scrollbar-bg-l1": "#1f1f1f",
    "--dsw-alias-scrollbar-hover-l1": "#2e2e2e",
    "--dsw-alias-tooltip-bg": "#1c1c1c",
    "--dsw-specific-bubble": "#0a0a0a",
    "--dsw-specific-bubble-highlight": "#141414",
    "--dsw-specific-sidebar-fill": "#000000",
    "--dsw-specific-sidebar-nav-item-active": "#141414",
    "--dsw-alias-bg-mask-1": "rgba(0, 0, 0, 0.5)",
    "--dsw-alias-bg-mask-2": "rgba(0, 0, 0, 0.2)",
    "--dsw-alias-bg-mask-3": "rgba(0, 0, 0, 0.48)",
    "--dsw-alias-bg-module-platform": "#0f0f0f",
    "--dsw-alias-bg-multi-select": "#0a0a0a",
    "--dsw-alias-bg-skeleton": "rgba(255, 255, 255, 0.08)",
    "--dsw-alias-border-l3": "rgba(255, 255, 255, 0.24)",
    "--dsw-alias-border-l4": "rgba(255, 255, 255, 0.32)",
    "--dsw-alias-border-inverted": "rgba(255, 255, 255, 0.12)",
    "--dsw-alias-button-info-fill": "#e0e0e0",
    "--dsw-alias-button-info-hover": "#c9c9c9",
    "--dsw-alias-button-elevated-fill": "#0f0f0f",
    "--dsw-alias-button-floating-fill": "#141414",
    "--dsw-alias-button-floating-hover": "#1c1c1c",
    "--dsw-alias-interactive-bg-hover-solid": "#1c1c1c",
    "--dsw-alias-interactive-bg-hover-danger": "rgba(248, 113, 113, 0.15)",
    "--dsw-alias-interactive-bg-hover-accent": "rgba(255, 255, 255, 0.24)",
    "--dsw-alias-label-caption": "#7b7b7b",
    "--dsw-alias-label-primary-inverted": "#000000",
    "--dsw-alias-label-primary-dimmed": "#a0a0a0",
    "--dsw-alias-label-dimmed": "#171717",
    "--dsw-alias-markdown-citation": "#141414",
    "--dsw-alias-markdown-code-segment-selected": "#171717",
    "--dsw-alias-markdown-code-segment-unselected": "#0a0a0a",
    "--dsw-alias-markdown-placeholder": "#171717",
    "--dsw-alias-scrollbar-bg-l2": "#1f1f1f",
    "--dsw-alias-scrollbar-hover-l2": "#2e2e2e",
    "--dsw-alias-state-success-secondary": "#6ee7b7",
    "--dsw-alias-state-warn-secondary": "#fcd34d",
    "--dsw-alias-state-error-secondary": "#fca5a5",
    "--dsw-alias-state-success-tertiary": "#052e16",
    "--dsw-alias-state-warn-tertiary": "#292406",
    "--dsw-alias-state-business-tertiary": "#1f1f1f",
    "--dsw-alias-toast-bg": "#1c1c1c",
    "--dsw-specific-input-major": "#0f0f0f",
    "--dsw-specific-login-input": "#0a0a0a",
    "--dsw-specific-menu": "#0f0f0f",
    "--dsw-specific-selector": "#0a0a0a",
    "--dsw-specific-sidebar-nav-item-hover": "#141414",
    "--dsw-specific-tip": "#0f0f0f",
  }),
});
